kind = "mobile"
previewPath = "/"
title = "السوري معك"
version = "1.0.0"
id = "artifacts/syrian-store"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22505

[services.development]
run = "pnpm --filter @workspace/syrian-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/syrian-store", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/syrian-store", "run", "serve" ]

[services.env]
PORT = "22505"
BASE_PATH = "/"
