const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1A6B2A",
    background: "#F7F5F0",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1A6B2A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0ECE3",
    secondaryForeground: "#1A1A1A",
    muted: "#EDE9E0",
    mutedForeground: "#7A7268",
    accent: "#C8960C",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E5E0D5",
    input: "#E5E0D5",
    gold: "#C8960C",
    goldLight: "#F5E6B0",
    greenLight: "#D4EDDA",
  },
  dark: {
    text: "#F0EDE6",
    tint: "#4CAF6A",
    background: "#121210",
    foreground: "#F0EDE6",
    card: "#1E1E1A",
    cardForeground: "#F0EDE6",
    primary: "#4CAF6A",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A24",
    secondaryForeground: "#F0EDE6",
    muted: "#2A2A24",
    mutedForeground: "#A09880",
    accent: "#D4A520",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2E2E28",
    input: "#2E2E28",
    gold: "#D4A520",
    goldLight: "#3A2E00",
    greenLight: "#1A3020",
  },
  radius: 12,
};

export default colors;
